Ember CLI v2.12.1
 - This is Step 1

 - Step 2: Accept the following commit for `ember-themed-syntax` - https://github.com/crodriguez1a/ember-themed-syntax/pull/5 then update this `package.json` to point to new `ember-themed-syntax` minor version release

 Currently this will throw error

```bash
Error: Cannot find module '/Users/alexdiliberto/Repos/ember-bulma/bower_components/ember/ember-template-compiler.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Class.htmlbarsOptions (/Users/alexdiliberto/Repos/ember-bulma/node_modules/ember-themed-syntax/node_modules/ember-cli-htmlbars/ember-addon-main.js:88:25)
    at Object.toTree (/Users/alexdiliberto/Repos/ember-bulma/node_modules/ember-themed-syntax/node_modules/ember-cli-htmlbars/ember-addon-main.js:31:43)
    at /Users/alexdiliberto/Repos/ember-bulma/node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (/Users/alexdiliberto/Repos/ember-bulma/node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
    at module.exports.preprocessTemplates (/Users/alexdiliberto/Repos/ember-bulma/node_modules/ember-cli-preprocess-registry/preprocessors.js:161:10)
```
This error goes away after the above referenced PR is accepted